# Required
version: 2

conda:
    environment: docs/readthedocs-env.yml
python:
    install:
        - method: setuptools
          path: .
submodules:
    include: all
    recursive: true

build:
  apt_packages:
    - pkg-config
    - curl
    - zip
    - unzip
    - tar
