# Required
version: 2

build:
  apt_packages:
    - pkg-config
    - curl
    - zip
    - unzip
    - tar

submodules:
    include: all
    recursive: true

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
    - method: pip
      path: .
      extra_requirements:
        - docs
