# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  apt-install:
    steps:
      - run:
          name: Install apt packages
          command: |
            sudo apt-get update
            sudo apt-get install build-essential curl zip unzip tar ninja-build
  merge:
    steps:
      - run:
          name: merge with upstream
          command: |
            echo $(git log -1 --pretty=%B) | tee gitlog.txt
            echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
            if [[ $(cat merge.txt) != "" ]]; then
              echo "Merging $(cat merge.txt)";
              git remote add upstream https://github.com/ErichZimmer/OpenPIV-Python-cxx.git;
              git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
              git fetch upstream main;
            fi     
jobs:
  # Build OpenPIV-Python-cxx from source
  build_openpiv_cxx:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - merge
      - apt-install

      - run:
          name: update submodules
          command: |
            git submodule init
            git submodule update --recursive
      
      - restore_cache:
          keys:
              - deps_ccache-{{ .Branch }}
              - deps_ccache

      - run:
          name: setup Python venv
          command: |
            pip install --upgrade pip
            pip install cmake
            pip install ninja
            pip install scikit-build  
            pip install numpy
            pip install imageio
            pip install scipy
            pip install matplotlib    
     
     - run:
          name: build OpenPIV-cxx
          command: |
            python setup.py build --inplace
    
    - save_cache:
          key: deps_ccache-{{ .Branch }}
          paths:
            - ~/.ccache
            - ~/.cache/pip

      - run:
          name: ccache performance
          command: |
            ccache -s
      
      - persist_to_workspace:
          root: ~/
          paths:
            - .
            
  # build documentation
  docs-build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - apt-install
      
      - run:
          name: Install dependencies
          command: pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.2
      
      - run:
          name: Build docs
          command: cd docs/ && make html
      
      - persist_to_workspace:
          root: docs/_build
          paths: html

workflows:
  version: 2
  default:
    jobs:
      - build_openpiv_cxx
      - docs-build

