name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_linux:
    name: Linux Build tests
    if: "github.repository == 'scipy/scipy' || github.repository == ''"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configuring Test Environment
        run: |
          sudo apt-get update
          sudo apt install pkg-config curl zip unzip tar
          free -m
          uname -a
          df -h
          ulimit -a
          set -e -o pipefail
          mkdir builds
          cd builds
      - name: update submodules
        run: |
          git submodule update --init --recursive
      - name: pip-packages
        run: |
          pip install numpy scikit-build cmake ninja imageio pytest
      - name: scikit-build
        run: python setup.py install
