name: Build wheels

on:
  # Manually trigger build
  workflow_dispatch:

  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
      types: [opened, labeled, reopened, synchronize]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.buildplat[0] }}, Python ${{ matrix.pyver }}
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build_wheels') }} || github.event_name != 'pull_request' }}
    runs-on: ${{ matrix.buildplat[0] }}
   
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # borrowed from NumPy
        buildplat:
        - [ubuntu-20.04, manylinux_x86_64]
        - [macos-10.14, macosx_*]
        - [windows-2019, win_amd64]
        - [windows-2019, win32]
        pyver: ["cp38"]

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: "recursive"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        with:
          output-dir: wheelhouse
          config-file: pyproject.toml
        env:
          # Build for cpython >= 3.7.
          CIBW_BUILD: ${{ matrix.pyver }}-${{ matrix.buildplat[1] }}
          
          # setup environment
          CIBW_BEFORE_BUILD_LINUX: "apt-get install build-essential pkg-config curl zip unzip tar"
          MACOSX_DEPLOYMENT_TARGET: "10.14"
          CIBW_BUILD_FRONTEND: "build"

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build_wheels') || github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install build requirements
        run: python3 -m pip install cmake ninja setuptools scikit-build numpy imageio --upgrade --progress-bar=off

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_pypi:
    name: Publish [PyPI]
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Check files
        run: ls -lR dist

      - name: Upload to TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && (github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')) }}
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
