name: Build wheels

on:
  # Trigger on pushes to the mainline branches and version tags. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
      - "master"
    tags:
      - "v*"

  pull_request:
      types: [opened, labeled, reopened, synchronize]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.os }}, Python ${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build_wheels') }} #|| github.event_name != 'pull_request' }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12, windows-2019]
        pyver: ["3.7", "3.8"]

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: "recursive"
        
      - name: Set up Python ${{ matrix.pyver }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.pyver }}
          
      - name: Install requirements
        run: |
          pip install numpy scikit-build cmake ninja imageio pytest wheel

      - name: Build wheel
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'build_wheels') }} #|| github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install build requirements
        run: python3 -m pip install cmake ninja setuptools scikit-build numpy imageio --upgrade --progress-bar=off

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_pypi:
    name: Publish [PyPI]
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Check files
        run: ls -lR dist

      - name: Upload to TestPyPI
        if: ${{ !startsWith(github.ref, 'refs/tags/v') && (github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')) }}
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
