name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black
          
      - run: |
          black .
